version: '3.7'

services:
  postgres:
    image: postgres:14.9-alpine3.18
    container_name: postgres
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    expose:
      - "5432"
  reports:
    build:
      dockerfile: web-service-api/Dockerfile
    container_name: reports
    depends_on:
      - postgres
    environment:
      - DB_SERVER=postgres
    ports:
      - '8081:8080'
