server:
  port: ${APP_PORT:8080}

spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.xml
    default-schema: public

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 20
        order_inserts: false

  datasource:
    url: jdbc:postgresql://postgres/postgres #${DB_URL}
    username: pguser #${DB_USER}
    password: pgpwd #${DB_PASSWORD}

app:
  swagger:
    title: Prod Processor
    description: Prod Processor
    version: 0.0.0.1-J17
    license: |-
      Innotech Group. Do not reproduce without permission in writing.
      Copyright (c) 2024 Innotech Group. All rights reserved.
    contact:
      email: IGudkov@inno.tech
      name: Гудков Игорь Николаевич
      url: https://inno.tech/ru/
    servers:
      - url: http://localhost:8081
        description: LOCAL
      - url: http://localhost:8081
        description: DSO
      - url: http://localhost:8081
        description: К3
      - url: http://localhost:8081
        description: К4
      - url: http://localhost:8081
        description: HOTFIX
      - url: http://localhost:8081
        description: PROD